/**:
  ros__parameters:
    csv_path: "/root/coche_ws/src/pure_pursuit_pkg/racelines/uc3m_hall_v0_waypoints.csv"  # Update this path
    min_distance : 0.1
    prev_x : 0.0
    prev_y : 0.0
    map_frame : "map"
    car_frame : "base_link"