/**:
  ros__parameters:
    min_lookahead_dist: 0.5
    max_lookahead_dist: 4.0
    lookahead_ratio: 8.0
    max_speed: 4.0
    min_speed: 0.4
    kp: 0.25
    max_steering_angle: 44
    window_size: 25
    max_lateral_acc: 5
    csv_path:  "/root/coche_ws/src/pure_pursuit_pkg/racelines/27-07.csv"
    map_frame: "map"
    car_frame: "base_link"
    odom_topic: "/odom"
    drive_topic: "/drive"
    goalpoint_topic: "/goalpoint"
    reactive: true